# Generated by Django 5.0.4 on 2024-04-05 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicByValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('_type', models.CharField(choices=[('Жанр', 'Жанр'), ('Группа', 'Группа'), ('Автор', 'Автор'), ('Альбом', 'Альбом'), ('Настроение', 'Настроение')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_by_genre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Музыка по жанру',
                'verbose_name_plural': 'Музыка по жанру',
                'db_table': 'music_by_genre',
            },
        ),
    ]
