# Generated by Django 5.0.4 on 2024-04-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicbyvalue',
            options={'verbose_name': 'Музыкальные предпочтения', 'verbose_name_plural': 'Музыкальные предпочтения'},
        ),
        migrations.AlterField(
            model_name='musicbyvalue',
            name='_type',
            field=models.CharField(choices=[('Жанр', 'Жанр'), ('Группа', 'Группа'), ('Автор', 'Автор'), ('Альбом', 'Альбом'), ('Настроение', 'Настроение'), ('Год выпуска', 'Год выпуска')], max_length=200),
        ),
        migrations.AlterModelTable(
            name='musicbyvalue',
            table='music_by_value',
        ),
    ]
